# Minecraft / loader
minecraft_version=1.21.1
loader_version=0.16.10

# Mod
mod_version=1.0.0
maven_group=com.example.ccballs
archives_base_name=ccballs

# Dependencias
fabric_api_version=0.107.0+1.21.1
fabric_kotlin_version=1.12.3+kotlin.2.0.21
# Version EXACTA de Cobblemon que vas a usar. Cambiala por la que tengas instalada
# (mirala en la carpeta mods/ o en la pagina de Modrinth: "Cobblemon x.y.z" para 1.21.1 Fabric)
cobblemon_version=1.7.3

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
