name: Build mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8

      - name: Compilar el mod
        working-directory: cobblemon-custom-balls
        run: gradle build

      - name: Publicar el .jar como descarga
        uses: actions/upload-artifact@v4
        with:
          name: cobblemon-custom-balls-jar
          path: cobblemon-custom-balls/build/libs/*.jar
